### PR TITLE
Detect a canceled request.

### PR DESCRIPTION
**Pull request by ton-katsu**
authorize-logged-in

### CODE REVIEW

**Comment by helenaford** [comment]
thanks for the p/r. looks great. Just looking into why the webhooks aren't working, and will get it merged :)

**Comment by ton-katsu** [comment]
Small fix. Best Regards.

**Comment by helenaford** [comment]
Mmm, not sure if it should be code: 'cancelled', with a different message. Is it useful to differentiate between them pressing back space vs the cancelled button (in the screenshot you attached above)? 

I guess it could be but just wondering why you changed it from cancelled to denied? Either way, it's good.

**Comment by ton-katsu** [comment]
I want to notify to the user with a toast when occurred some errors. The request that is cancelled by the user is not a error. The back space is returned 'FlutterAuthExceptionCode.cancelled' . However, the cancelled button is returned 'FlutterAuthExceptionCode.login' .

e.g.)
https://github.com/twitter-archive/twitter-kit-ios:
The cancelled button: return 'canceled'.
https://github.com/twitter-archive/twitter-kit-android:
The cancelled button: return 'error'.

ref above)
https://github.com/roughike/flutter_twitter_login/blob/master/lib/flutter_twitter_login.dart#L149-L154

I used to use 'flutter_twitter_login'. However, the canceled button is return a error on the Android.

**Comment by helenaford** [comment]
Yea, I totally understand why it needs to return something other than login. But, I'm trying to work out why did you go from 'cancelled' (in commit 1) to 'denied' (in commit 2)?  For twitter, to return denied, is that only when the user clicks the cancel button?

**Comment by ton-katsu** [comment]
The query parameter of the cancel button link is 'denied=xxxx'. 
How to handle about 'denied=xxxx', it would be better decide by a user using this library.

My application handle as cancel when 'denied' and 'Navigator.pop()'. :relaxed:


> For twitter, to return denied, is that only when the user clicks the cancel button?

Probably. However, it does not ducumented. If there is a problem, this PR close please.

**Pull request merged**
